<<<<<<< HEAD
model:
  mediapipe:
    detection_conf: 0.5
    tracking_conf: 0.5
smoothing:
  enabled: true
  type: "ema"          # or "one_euro"
  ema_alpha: 0.25
confidence:
  min_visibility: 0.5
metrics:
  asymmetry_warn: 0.25
  trunk_lean_warn_deg: 30
server:
  host: "0.0.0.0"
  port: 5000
=======
# config/settings.yaml

# … existing entries …

services:
  gemini:
    url: "https://api.example.com/v1/gemini/generate"   # replace with real Gemini endpoint
    key: "YOUR_GEMINI_API_KEY"
    model: "gemini-small"
  elevenlabs:
    url: "https://api.elevenlabs.io/v1/text-to-speech/Alloy"  # Alloy voice
    key: "YOUR_ELEVENLABS_API_KEY"
>>>>>>> feature/gemini-elevenlabs-audio
